import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Nextjs Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About Us</a>
          
        </nav>
      </header>
      <main className={styles.main}>
      {data && data.map(ev => (
             <a href={`/events/${ev.id}`} key={ev.id}>
             <img src={ev.image} alt="" />
             <h2>{ev.title}</h2>
             <p>{ev.description}</p>
           </a>
      ))}

      
      </main>

      <footer></footer>
    </>
  )
}

export async function getServerSideProps() {

  const { events_categories } = await import('/data/data.json')
  console.log(events_categories)

  return {
    props: {
      title: 'Hello everyone!'
    }
  }
}

